version: '3'
services:
   proxy:
      image: jwilder/nginx-proxy
      container_name: proxy
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
         - "80:80"
         - "443:443"
      networks:
         - frontend
   wp:
      depends_on:
         - db
      image: wordpress
      container_name: wp
      restart: always
      volumes:
         - ./html/wp-content:/var/www/html/wp-content
      expose:
         - "80"
         - "443"
      networks:
         - frontend
         - backend
      environment:
         VIRTUAL_HOST: wp.local
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_USER: GummyChief
         WORDPRESS_DB_PASSWORD: 2NinjasAreStillAlive!
         WORDPRESS_DB_NAME: FastWalrus
   db:
      image: mysql
      container_name: db
      restart: always
      volumes:
         - db_data:/var/lib/data
      expose:
         - "3306"
      networks:
         - backend
      environment:
         MYSQL_ROOT_PASSWORD: OceanBlueIsThe3rdColor!
         MYSQL_USER: GummyChief
         MYSQL_PASSWORD: 2NinjasAreStillAlive!
         MYSQL_DATABASE: FastWalrus
   pma:
      depends_on:
         - db
      image: phpmyadmin/phpmyadmin
      container_name: pma
      restart: always
      expose:
         - "80"
         - "443"
      networks:
         - frontend
         - backend
      environment:
         VIRTUAL_HOST: pma.local
         PMA_HOST: db
         MYSQL_ROOT_PASSWORD: OceanBlueIsThe3rdColor!
volumes:
   db_data:
networks:
   frontend:
   backend: